// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCje9LHbqQTNj7q3v5FIQSbGkTtiGY3URs',
    appId: '1:1064348924112:web:4fdefd1f6e97ca5eb786d5',
    messagingSenderId: '1064348924112',
    projectId: 'docdoc-32615',
    authDomain: 'docdoc-32615.firebaseapp.com',
    storageBucket: 'docdoc-32615.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB548cqzRtgpXOt-g2e9oAPvOID6V4Xuuo',
    appId: '1:1064348924112:android:6ccaf1ba9c917064b786d5',
    messagingSenderId: '1064348924112',
    projectId: 'docdoc-32615',
    storageBucket: 'docdoc-32615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpFcNfVHyWBQvErZ885jDUNF8-Y-GzXg',
    appId: '1:1064348924112:ios:7af1da15c719fee6b786d5',
    messagingSenderId: '1064348924112',
    projectId: 'docdoc-32615',
    storageBucket: 'docdoc-32615.firebasestorage.app',
    iosBundleId: 'com.example.duc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpFcNfVHyWBQvErZ885jDUNF8-Y-GzXg',
    appId: '1:1064348924112:ios:7af1da15c719fee6b786d5',
    messagingSenderId: '1064348924112',
    projectId: 'docdoc-32615',
    storageBucket: 'docdoc-32615.firebasestorage.app',
    iosBundleId: 'com.example.duc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCje9LHbqQTNj7q3v5FIQSbGkTtiGY3URs',
    appId: '1:1064348924112:web:9465f7a1fb530c8bb786d5',
    messagingSenderId: '1064348924112',
    projectId: 'docdoc-32615',
    authDomain: 'docdoc-32615.firebaseapp.com',
    storageBucket: 'docdoc-32615.firebasestorage.app',
  );
}
